pattern: circular
radius: 30
height: 75
thickness: 12
x_height: 5
x_width: 5
contact_fraction_h: 0.3
contact_fraction_v: 0.3
frame_len_top: 2
frame_len: 14
bottom: true
fullness_function: by_the_frame