pattern: spherical
radius: 50
height: 140
thickness: 18
x_height: 50
x_width: 40
contact_fraction_h: 0.3
contact_fraction_v: 0.3
frame_len_top: 0
frame_len_bottom: 2
fullness_function: glass
warp_function: glass
bottom: true
