pattern: spiral
spiral_initial_radius: 90
spiral_layers_gap: 0.45
height: 220
spiral_length: 2010

thickness: 0.45
x_height: 7
x_width: 4
contact_fraction_h: 0.3
contact_fraction_v: 0.3
frame_len: 6

precision: 2