pattern: spiral
spiral_initial_radius: 100
spiral_layers_gap: 0.45
height: 160
spiral_length: 1100

thickness: 0.6
x_height: 6
x_width: 3.5
contact_fraction_h: 0.3
contact_fraction_v: 0.3
frame_len: 3
